
device_search_term: 'Logitech Gamepad F710'


#Map the button codes to the button names
button_map:
  304: 'A'
  305: 'B'
  307: 'X'
  308: 'Y'
  312: 'LEFT_BOTTOM_TRIGGER'
  310: 'LEFT_TOP_TRIGGER'
  313: 'RIGHT_BOTTOM_TRIGGER'
  311: 'RIGHT_TOP_TRIGGER'
  317: 'LEFT_STICK_PRESS'
  318: 'RIGHT_STICK_PRESS'
  314: 'SELECT'
  315: 'START'
  0: 'LEFT_STICK_X'
  1: 'LEFT_STICK_Y'
  3: 'RIGHT_STICK_X'
  4: 'RIGHT_STICK_Y'
  16: 'PAD_RIGHT'
  16: 'PAD_LEFT'
  17: 'PAD_UP'
  17: 'PAD_DOWN'


joystick_max_value: 32768



